### ISSUE TITLE
ssh to teaching cluster

### ISSUE THREAD

**Issue by kevinrue** [kevinrue/wimm_ccb_docs#265]
## On local network

Set up your WIMM IT password (<https://management.imm.ox.ac.uk/>).

```bash
ssh abcd1234@imm-obds
```

When prompted type your WIMM IT password.

**Comment by kevinrue** [comment]
## SSH config

Step 1. Create SSH key pair

```sh
ssh-keygen -t ecdsa -b 521
```

Step 2. Edit `.ssh/config`

```sh
Host obds
     HostName imm-obds
     User abcd1234
     IdentityFile ~/.ssh/id_ecdsa
     LocalForward localhost:8787 localhost:8787
```

Step 3. Copy SSH public key to `imm-obds`

```sh
ssh-copy-id -i ~/.ssh/id_ecdsa obds
```

You will be prompted for the password, possibly twice (logging in, adding the key).

Step 4. Connect to `imm-obds`

```sh
ssh obds
```

**Comment by kevinrue** [comment]
## On VPN

### Single command

```sh
ssh -J abcd1234@bastion.imm.ox.ac.uk abcd1234@imm-obds
```

### Using SSH key 

Step 1. Edit `.ssh/config` 

```
Host bastion
    HostName bastion.imm.ox.ac.uk
    User abcd1234
    IdentityFile ~/.ssh/id_ecdsa

Host obds-bastion
    HostName imm-obds
    User abcd1234
    IdentityFile ~/.ssh/id_ecdsa
    # for RStudio
    LocalForward localhost:8787 localhost:8787
    # via Bastion
    ProxyCommand ssh abcd1234@bastion.imm.ox.ac.uk nc %h %p
```

Step 2. Copy SSH public key to `bastion`

```sh
ssh-copy-id -i ~/.ssh/id_ecdsa bastion
```

Notes:

- Uses ssh config.

Step 3.  Copy SSH public key to `imm-obds` via `bastion`

```sh
ssh-copy-id -o ProxyJump=bastion obds
```

Notes:

- Uses ssh config.
- The passphrase is asked three times (bastion, imm-obds, permission to add key).

Step 4. Connect to `imm-obds` via `bastion` 

```sh
ssh obds-bastion
```

Note: The passphrase is asked twice.

**Comment by liezeltamon** [comment]
> 

This works for me

**Comment by liezeltamon** [comment]
> ## On VPN
> ### Single command
> ```shell
> ssh -J abcd1234@bastion.imm.ox.ac.uk abcd1234@imm-obds
> ```
> 
> ### Using SSH key
> Step 1. Edit `.ssh/config`
> 
> ```
> Host bastion
>     HostName bastion.imm.ox.ac.uk
>     User abcd1234
>     IdentityFile ~/.ssh/id_ecdsa
> 
> Host obds-bastion
>     HostName imm-obds
>     User abcd1234
>     IdentityFile ~/.ssh/id_ecdsa
>     # for RStudio
>     LocalForward localhost:8787 localhost:8787
>     # via Bastion
>     ProxyCommand ssh abcd1234@bastion.imm.ox.ac.uk nc %h %p
> ```
> 
> Step 2. Copy SSH public key to `bastion`
> 
> ```shell
> ssh-copy-id -i ~/.ssh/id_ecdsa bastion
> ```
> 
> Notes:
> 
> * Uses ssh config.
> 
> Step 3. Copy SSH public key to `imm-obds` via `bastion`
> 
> ```shell
> ssh-copy-id -o ProxyJump=bastion obds
> ```
> 
> Notes:
> 
> * Uses ssh config.
> * The passphrase is asked three times (bastion, imm-obds, permission to add key).
> 
> Step 4. Connect to `imm-obds` via `bastion`
> 
> ```shell
> ssh obds-bastion
> ```
> 
> Note: The passphrase is asked twice.

This works for me! and can definitely simply bastion i.e.

```
ProxyCommand ssh bastion nc %h %p
```
